spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gujian1992/config.git
          search-paths: config
server:
  port: 8090